[build]
# 設置正確的根目錄為 my-project
workingDirectory = "my-project"
# 使用 Railway 原生 Node.js 構建
command = "npm ci --silent"

[deploy]
workingDirectory = "my-project"
# 直接啟動 develop 模式避免構建問題
startCommand = "npm run develop"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "1337"
HOST = "0.0.0.0"

[variables]
DATABASE_CLIENT = "postgres"

# 明確指定為 Node.js 專案
[build.env]
NODE_VERSION = "20" 