[build]
# 部署 Next.js 前端應用
command = "npm ci && npm run build"

[deploy]
# 啟動 Next.js 生產服務器
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "3000"

# Next.js 環境變數
[variables]
NEXT_PUBLIC_API_URL = "https://api.example.com" 