[build]
# 跳過構建命令，直接使用 Dockerfile
command = "echo 'Using Dockerfile for build'"

[deploy]
# 使用 develop 模式避免構建問題
startCommand = "npm run develop"
healthcheckPath = "/"
healthcheckTimeout = 300

[env]
NODE_ENV = "production"
PORT = "1337"
HOST = "0.0.0.0"

[variables]
DATABASE_CLIENT = "postgres" 